route:
  spec:
    host: "websockets.buildingpermit.gov.bc.ca"

anycable-go:
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
