module JwtAuthenticatable
  extend ActiveSupport::Concern

  included do
    def self.jwt_revocation_strategy
      self
    end
  end

  # Adding the Keycloak ID token to the JWT payload
  # This is a callback used by Devise::JWT that gets called when a JWT is generated
  # The token is generated by Warden::JWTAuth::UserEncoder
  def on_jwt_dispatch(_token, payload)
    # Add the Keycloak ID token if it's present
    if self.keycloak_id_token.present?
      # Store the token for logout verification
      payload[:kc_id_token] = self.keycloak_id_token

      # Clear the token from memory after use
      self.keycloak_id_token = nil
    end
  end
end
