import { StyleSheet } from "@react-pdf/renderer"
import { theme } from "../../../../../styles/theme"

export const styles = StyleSheet.create({
  panelContainer: {
    borderWidth: 0.75,
    borderColor: theme.colors.greys.grey02,
    borderRadius: 6,
    width: "100%",
  },
  panelHeader: {
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 18,
    paddingRight: 18,
    backgroundColor: theme.colors.greys.grey04,
    color: theme.colors.text.primary,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomWidth: 0.75,
    borderColor: theme.colors.greys.grey02,
  },
  panelHeaderText: {
    fontSize: 15,
    fontWeight: 700, // TODO
  },
  panelBody: {
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 9,
    paddingBottom: 9,
    display: "flex",
    flexDirection: "column",
    width: "100%",
    gap: 12,
    borderRadius: 6,
  },
  panelBodyTitleText: {
    fontSize: 13.5,
    fontWeight: 700,
  },
  labelText: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    fontSize: 10.5,
    color: theme.colors.text.primary,
    marginBottom: 3,
  },
  input: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 9,
    paddingRight: 9,
    borderRadius: 3,
    minHeight: 30,
    backgroundColor: theme.colors.greys.grey04,
    color: theme.colors.text.primary,
    fontSize: 10.5,
  },
  complianceSummaryContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 4.5,
    borderWidth: 0.75,
    borderColor: theme.colors.greys.grey02,
  },
  complianceSummaryHeading: {
    fontSize: 15,
    fontWeight: 700,
  },
  stepFormControl: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 6,
  },
  stepLabel: {
    fontSize: 12,
  },
  stepBox: {
    display: "flex",
    alignItems: "center",
    borderRadius: 4.5,
    backgroundColor: theme.colors.semantic.infoLight,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 4.5,
    paddingBottom: 4.5,
    fontWeight: 700,
    fontSize: 15,
  },
  stepsContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    width: "100%",
  },
  stepContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    width: "100%",
  },
  requiredText: {
    fontSize: 8,
    textAlign: "center",
  },
  stepsStepBox: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
  },
})
