redis:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: bb18ab-prod/redis
    tag: 7.2.4-debian-12-r9
  sentinel:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
    image:
      registry: image-registry.openshift-image-registry.svc:5000
      repository: "bb18ab-prod/redis-sentinel"
      tag: "7.2.4-debian-12-r7"
  replica:
    replicaCount: 3
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
