# Apply base configuration from values.yaml and make the necessary overrides in custom-values-example.yaml
# helm upgrade --install new-hippo-ha . -f values.yaml -f custom-values-example.yaml

fullnameOverride: ha-postgres-crunchydb
shutdown: false # Set to true to enable shutdown of the cluster before upgrading postgres major versions.

labels:
  app.kubernetes.io/instance: ha-postgres-crunchydb

postgresVersion: 16

standby:
  enabled: false # Disable for initial bootstrap restore
  repoName: repo2

instances:
  replicas: 1
  dataVolumeClaimSpec:
    storage: 600Mi

dataSource:
  enabled: false  # Enable for initial bootstrap restore
  createS3Secret: false  # External Secrets will manage the secret
  secretName: s3-creds
  repo:
    path: "/habackup_20250922020010"
    s3:
      bucket: "housing-bssb-ex-permithub-dbbk-dev-bkt"
      endpoint: "https://housing-bssb-ex.objectstore.gov.bc.ca"

pgBackRest:
  global:
    repo2-s3-verify-tls: "n"  # Add this to disable TLS verification issues
    repo2-retention-archive: "1"  # Number of backups worth of WAL to retain
    repo2-retention-archive-type: full  # Base retention on full backups
  retention: "1"
  retentionFullType: count
  retentionS3: "1"
  retentionFullTypeS3: time
  repos:
    schedules:
      full: "0 4 * * *"  # Feb 31st never exists - effectively disabled
      incremental: "0 0,6,12,16,20 * * *"  # Feb 31st never exists - effectively disabled
    volume:
      storage: 100Mi

  # repo2 - S3 configuration for WAL archive access from source system
  s3:
    enabled: true  # Disable repo2 for standby - read-only access no WAL archiving
    createS3Secret: false  # External Secrets will manage the secret
    s3Secret: s3-creds
    # the path start with /, it will be created under bucket if it doesn't exist
    s3Path: "/new_habackup_dev"
    # bucket specifies the S3 bucket to use,
    bucket: "housing-bssb-ex-permithub-dbbk-dev-bkt"
    # endpoint specifies the S3 endpoint to use.
    endpoint: "https://housing-bssb-ex.objectstore.gov.bc.ca"
    # Disable backup schedules for repo2 - this is read-only for standby
    fullSchedule: "0 9 * * *"  # Feb 31st never exists - effectively disabled
    incrementalSchedule: "0 0 31 2 *"  # Feb 31st never exists - effectively disabled

patroni:
  postgresql:
    parameters:
      min_wal_size: 32MB # Sets the minimum size to shrink the WAL files to 
      checkpoint_timeout: 60min  # Reduce checkpoint frequency

proxy:
    pgBouncer:
      replicas: 1