
global:
  imageRegistry: image-registry.openshift-image-registry.svc:5000/bb18ab-dev
  imagePullSecrets: []
  storageClass: ""

defaultResources:
  limits:
    memory: 200Mi
  requests:
    cpu: 10m
    memory: 25Mi

matomo:
  image: matomo:5.12.0-fpm
  runAsUser: null
  resources:
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      memory: 2Gi
  site:
    name: Matomo
    url: <REDACTED>
  ingress:
    enabled: false
  dashboard:
    replicas: 1
    hostname: <REDACTED>
    tls: true
    firstuser:
      username: admin
      email: BPH.Dev@gov.bc.ca
  tracker:
    enabled: true
    replicas: 1
    hostname: <REDACTED>
    tls: true
    phpFpmCommand: /usr/local/sbin/php-fpm
    # -- Main "matomo" (php-fpm) container in the tracker pod.
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 1Gi
  cli:
    enabled: false
    replicas: 0
  queuedTrackingMonitor:
    enabled: false
  queuedTrackingProcess:
    enabled: false
    replicas: 0
  cronJobs:
    coreArchive:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
    scheduledTasks:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          memory: 1Gi

nginx:
  image: nginx:1.21.6
  runAsUser: null

fpmExporter:
  image: php-fpm_exporter:2.2.0

db:
  enabled: true
  image: mariadb:11.4
  collation: "utf8mb4_uca1400_ai_ci"
  storage:
    size: 1Gi
    storageClass: ""
    mountPath: /var/lib/mysql
  temp:
    enabled: true
    mountPath: /tmp
    sizeLimit: 256Mi
  auth:
    createSecret: true
    rootPassword: ""
  # -- "mariadb" container.
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 1Gi
backup:
  enabled: false

openshift:
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

networkPolicy:
  enabled: true
  allowOpenShiftIngress: true
  ingressNamespaceSelector:
    matchLabels:
      network.openshift.io/policy-group: ingress
