---
{{- if .Values.matomo.cronJobs.scheduledTasks.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: matomo-jobs-scheduled-tasks
  namespace: {{.Release.Namespace}}
  {{- template "matomo.labels" .Values.matomo.cronJobs.scheduledTasks.labels }}
spec:
  schedule: {{quote .Values.matomo.cronJobs.scheduledTasks.schedule}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{.Values.matomo.cronJobs.scheduledTasks.activeDeadlineSeconds}}
      template:
        metadata:
          labels:
            app: matomo-jobs-scheduled-tasks
        spec:
{{ include "matomo.init" . | nindent 10 }}
          containers:
          - name: matomo-jobs-scheduledtasks
            image: {{ include "matomo.image" (dict "registry" (.Values.matomo.imageRegistry | default .Values.global.imageRegistry) "image" .Values.matomo.image) }}
            imagePullPolicy: Always
            {{- include "matomo.securityContext" (dict "runAsUser" .Values.matomo.runAsUser) | nindent 12 }}
            command: [ 'sh' , '-c' , {{quote .Values.matomo.cronJobs.scheduledTasks.command}} ]
            env:
            - name: MARIADB_MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
{{ include "matomo.license" . | nindent 12 }}
            {{- include "matomo.resources" (dict "resources" .Values.matomo.cronJobs.scheduledTasks.resources "defaultResources" .Values.defaultResources) | nindent 12 }}
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
              - name: matomo-common-config
                mountPath: /var/www/html/config/common.config.ini.php
                subPath: common.config.ini.php
                readOnly: true
              - name: matomo-scheduledtasks-php
                mountPath: /usr/local/etc/php/conf.d/zz-global.ini
                subPath: zz-global.ini
          restartPolicy: OnFailure
{{ include "matomo.images.pullSecrets" ( dict "images" (list .Values.matomo) "global" .Values.global) | nindent 10 }}
      {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name: matomo-configuration
            configMap:
              name: matomo-configuration
          - name: matomo-common-config
            configMap:
              name: matomo-configuration
              items:
              - key: common.config.ini.php
                path: common.config.ini.php
          - name: static-data
            emptyDir: {}
          - name: matomo-scheduledtasks-php
            configMap:
              name: matomo-scheduledtasks-php
{{- end -}}
