{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.hostname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: matomo-db
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app: matomo-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.hostname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: matomo-db
spec:
  serviceName: {{ .Values.db.hostname }}
  replicas: 1
  selector:
    matchLabels:
      app: matomo-db
  template:
    metadata:
      labels:
        app: matomo-db
    spec:
      containers:
        - name: mariadb
          image: {{ include "matomo.image" (dict "registry" (.Values.db.imageRegistry | default .Values.global.imageRegistry) "image" .Values.db.image) }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
            - name: MARIADB_DATABASE
              value: {{ .Values.db.name | quote }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
{{ include "matomo.resources" (dict "resources" .Values.db.resources "defaultResources" .Values.defaultResources) | nindent 10 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.db.storage.mountPath | quote }}
{{ include "matomo.images.pullSecrets" ( dict "images" (list .Values.db) "global" .Values.global) | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- $storageClass := .Values.db.storage.storageClass | default .Values.global.storageClass }}
        {{- if $storageClass }}
        storageClassName: {{ $storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.db.storage.size | quote }}
{{- end }}
