## Elasticsearch parameters
elasticsearch:
  master:
    replicaCount: 3
    heapSize: "512m"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "500Mi"
  data:
    replicaCount: 3
    heapSize: "800m"
    resources:
      requests:
        cpu: "200m"
        memory: "800Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "2Gi"
