## Elasticsearch parameters
elasticsearch:
  master:
    replicaCount: 3
    heapSize: "512m"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "1024Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "500Mi"
  data:
    replicaCount: 2
    heapSize: "1024m"
    resources:
      requests:
        cpu: "200m"
        memory: "1024Mi"
      limits:
        cpu: "400m"
        memory: "2048Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "2Gi"
