## Elasticsearch parameters
elasticsearch:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: bb18ab-prod/elasticsearch
    tag: 8.12.2-debian-12-r0
  master:
    replicaCount: 3
    heapSize: "512m"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "500Mi"
  data:
    replicaCount: 3
    heapSize: "800m"
    resources:
      requests:
        cpu: "200m"
        memory: "800Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "2Gi"
