class OverheatingCodeBlueprint < Blueprinter::Base
  identifier :id

  fields :status,
         :issued_to,
         :project_number,
         :full_address,
         :pid,
         :building_model,
         :site_name,
         :lot,
         :postal_code,
         :submittal_type,
         :units,
         :dimensional_info_based_on,
         :attachment,
         :number_of_stories,
         :has_basement,
         :weather_location,
         :ventilated,
         :hrv_erv,
         :ase_percentage,
         :atre_percentage,
         :front_facing,
         :front_facing_assumed,
         :air_tightness_category,
         :air_tightness_ach50,
         :air_tightness_ela10,
         :air_tightness_assumed,
         :wind_exposure,
         :wind_sheltering,
         :internal_shading,
         :internal_shading_assumed,
         :occupants,
         :occupants_assumed,
         :calculation_units,
         :heating_outdoor_temp,
         :heating_indoor_temp,
         :mean_soil_temp,
         :soil_conductivity,
         :water_table_depth,
         :slab_fluid_temp,
         :cooling_outdoor_temp,
         :cooling_indoor_temp,
         :daily_temp_range,
         :latitude,
         :above_grade_walls,
         :below_grade_walls,
         :floors_on_soil,
         :ceilings,
         :exposed_floors,
         :doors,
         :windows,
         :skylights,
         :minimum_heating_capacity,
         :nominal_cooling_capacity,
         :minimum_cooling_capacity,
         :maximum_cooling_capacity,
         :room_results,
         :ventilation_loss,
         :latent_gain,
         :created_at,
         :updated_at

  association :creator, blueprint: UserBlueprint
  association :jurisdiction, blueprint: JurisdictionBlueprint, view: :base
end
