STAGE: dev

route:
  spec:
    host: "dev.buildingpermit.gov.bc.ca"

pvc:
  spec:
    resources:
      requests:
        storage: 250Mi

deployments:
  - process: web
    replicaCount: 1
    spec:
      containers:
        includeCommand: false
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 750m
            memory: 512Mi
  - process: worker
    replicaCount: 1
    spec:
      containers:
        includeCommand: true
        args:
          - >-
            set -a; . /vault/secrets/secrets.env; set +a; exec bundle exec sidekiq
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
  - process: anycable-rpc
    replicaCount: 1
    spec:
      containers:
        includeCommand: true
        args:
          - >-
            set -a; . /vault/secrets/secrets.env; set +a; exec bundle exec anycable --rpc-host=0.0.0.0:50051
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
