apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronJob.name }}
spec:
  schedule: {{ .Values.cronJob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clamav
              image: "{{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}"
              imagePullPolicy: {{ .Values.cronJob.imagePullPolicy }}
              command: {{ .Values.cronJob.command | toJson }}
              resources:
                {{- toYaml .Values.cronJob.resources | nindent 16 }}
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
