export const FILE_UPLOAD_CHUNK_SIZE = import.meta.env.VITE_FILE_UPLOAD_CHUNK_SIZE || 10
export const FILE_UPLOAD_CHUNK_SIZE_IN_BYTES = FILE_UPLOAD_CHUNK_SIZE * 1024 * 1024
export const MAX_NUMBER_OF_PARTS = (import.meta.env.VITE_FILE_UPLOAD_MAX_SIZE || 100) / FILE_UPLOAD_CHUNK_SIZE
