crunchy-postgres:
  instances:
    replicas: 3
    dataVolumeClaimSpec:
      storage: 2Gi
    requests:
      cpu: 200m
      memory: 256Mi
    limits: # wanted to just leave limits blank here, but the underlying chart speciffies it, so instead just specify a large number
      cpu: 2
      memory: 8Gi
    replicaCertCopy:
      requests:
        cpu: 10m
        memory: 32Mi

  dataSource:
    enabled: false
    # should have the same name and contain the same keys as the pgbackrest secret
    secretName: s3-pgbackrest
    repo:
      name: repo2
      path: "/habackup_new"
      s3:
        bucket: "bucketName"
        endpoint: <REDACTED>
        region: "not-used"
      stanza: db

  pgBackRest:
    retention: "1"
    retentionS3: "730" # Ideally a larger number such as backups for 30 days
    retentionFullType: count # Type of retention for full backups
    retentionFullTypeS3: time # Type of retention for full backups
    retentionArchive: "2" # Number of backups worth of continuous WAL to retain
    retentionArchiveType: full # Type of retention for WAL archives
    repos:
      volume:
        storage: 1Gi
    repoHost:
      requests:
        cpu: 1m
        memory: 64Mi
    sidecars:
      requests:
        cpu: 1m
        memory: 64Mi

    s3:
      enabled: true
      createS3Secret: true
      # the s3 secret name
      s3Secret: s3-pgbackrest
      # the path start with /, it will be created under bucket if it doesn't exist
      s3Path: "/habackup_new"
      # s3UriStyle is host or path
      s3UriStyle: path
      # bucket specifies the S3 bucket to use,
      bucket:  <REDACTED>
      # endpoint specifies the S3 endpoint to use.
      endpoint:  <REDACTED>
      # region specifies the S3 region to use. If your S3 storage system does not
      # use "region", fill this in with a random value.
      region: "ca-central-1"
      # key is the S3 key. This is stored in a Secret.
      # Please DO NOT push this value to GitHub
      key:  <REDACTED>
      # keySecret is the S3 key secret. This is stored in a Secret.
      # Please DO NOT push this value to GitHub
      keySecret:  <REDACTED>
      fullSchedule: 0 9 * * *
      incrementalSchedule: "0 0 31 2 *" #set to FEB 31st so this will never run
      
  patroni:
    postgresql:
      parameters:
        shared_buffers: 16MB # default is 128MB; a good tuned default for shared_buffers is 25% of the memory allocated to the pod
        wal_buffers: "64kB" # this can be set to -1 to automatically set as 1/32 of shared_buffers or 64kB, whichever is larger
        min_wal_size: 32MB
        max_wal_size: 64MB # default is 1GB
        max_slot_wal_keep_size: 128MB # default is -1, allowing unlimited wal growth when replicas fall behind

  proxy:
    pgBouncer:
      replicas: 2
      requests:
        cpu: 50m
        memory: 64Mi
