name: Deploy a branch to DEV

# 🔐 Set least-privilege permissions for the entire workflow
permissions:
  contents: read
  deployments: write
  pull-requests: write

on:
  # push:
  #   branches: ["develop"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        required: true
        default: "develop"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker Rails / React application
    environment: dev

    steps:
      - name: Checkout Workflow Code
        uses: actions/checkout@v4

      - name: Deploy to OpenShift
        uses: ./.github/actions/openshift-deploy
        with:
          branch: ${{ github.event.inputs.branch }}
          github_token: ${{ github.token }}
          deployment_environment: dev
          environment_label: Dev
          image_name: dev-hous-permit-portal
          build_args: |
            VITE_ENABLE_TEMPLATE_FORCE_PUBLISH=${{ vars.VITE_ENABLE_TEMPLATE_FORCE_PUBLISH }}
            VITE_BASIC_BCEID_REGISTRATION_URL=${{ vars.VITE_BASIC_BCEID_REGISTRATION_URL }}
            VITE_BUSINESS_BCEID_REGISTRATION_URL=${{ vars.VITE_BUSINESS_BCEID_REGISTRATION_URL }}
            VITE_BCSC_REGISTRATION_URL=${{ vars.VITE_BCSC_REGISTRATION_URL }}
            VITE_BCEID_URL=${{ vars.VITE_BCEID_URL }}
            VITE_BCEID_PARTNER_URL=${{ vars.VITE_BCEID_PARTNER_URL }}
            VITE_RELEASE_VERSION=dev-${{ github.event.inputs.branch }}-${{ github.sha }}
            VITE_SITEMINDER_LOGOUT_URL=${{ vars.VITE_SITEMINDER_LOGOUT_URL }}
            VITE_KEYCLOAK_LOGOUT_URL=${{ vars.VITE_KEYCLOAK_LOGOUT_URL }}
            VITE_POST_LOGOUT_REDIRECT_URL=${{ vars.VITE_POST_LOGOUT_REDIRECT_URL }}
            VITE_QA_MODE=${{ vars.VITE_QA_MODE }}
          registry_url: ${{ secrets.REGISTRY_URL }}
          builder_username: ${{ secrets.BUILDER_USERNAME }}
          builder_token: ${{ secrets.BUILDER_TOKEN }}
