name: Deploy a branch to PRODUCTION

# 🔐 Set least-privilege permissions for the entire workflow
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        required: true
        default: "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker Rails / React application
    environment: prod

    steps:
      - name: Enforce branch match
        if: github.event.inputs.branch != github.ref_name
        run: |
          echo "You are trying to deploy '${{ github.event.inputs.branch }}' but running this workflow from '${{ github.ref_name }}'."
          echo "You must run this workflow from the same branch you are deploying."
          exit 1

      - name: Check if user is authorized
        run: |
          AUTHORIZED_USERS="${{ secrets.AUTHORIZED_USERS }}"
          if [[ ! ",$AUTHORIZED_USERS," =~ ",${{ github.actor }}," ]]; then
            echo "Error: ${GITHUB_ACTOR} is not authorized to trigger this workflow"
            exit 1
          fi

      - name: Deploy to OpenShift
        uses: ./.github/actions/openshift-deploy
        with:
          branch: ${{ github.event.inputs.branch }}
          environment_label: Production
          image_name: prod-hous-permit-portal
          build_args: |
            VITE_BASIC_BCEID_REGISTRATION_URL=${{ vars.VITE_BASIC_BCEID_REGISTRATION_URL }}
            VITE_BUSINESS_BCEID_REGISTRATION_URL=${{ vars.VITE_BUSINESS_BCEID_REGISTRATION_URL }}
            VITE_BCSC_REGISTRATION_URL=${{ vars.VITE_BCSC_REGISTRATION_URL }}
            VITE_BCEID_URL=${{ vars.VITE_BCEID_URL }}
            VITE_BCEID_PARTNER_URL=${{ vars.VITE_BCEID_PARTNER_URL }}
          registry_url: ${{ secrets.REGISTRY_URL }}
          builder_username: ${{ secrets.BUILDER_USERNAME }}
          builder_token: ${{ secrets.BUILDER_TOKEN }}
