name: Deploy a branch to TEST

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        required: true
        default: "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker Rails / React application
    environment: test

    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          lfs: true
      - name: Update GITHUB_SHA with checked-out commit SHA
        run: echo "GITHUB_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Confirm branch and SHA to deploy
        run: |
          echo "Deploying branch: ${{ github.event.inputs.branch }} @ ${{ env.GITHUB_SHA }} to Test"
      - name: Build Docker Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: test-hous-permit-portal
          tags: latest ${{ env.GITHUB_SHA }}
          labels: |
            app=test-hous-permit-portal
            git-sha=${{ env.GITHUB_SHA }}
          containerfiles: ./devops/docker/app/Dockerfile
          build-args: |
            VITE_ENABLE_TEMPLATE_FORCE_PUBLISH=${{ vars.VITE_ENABLE_TEMPLATE_FORCE_PUBLISH }}
            VITE_BASIC_BCEID_REGISTRATION_URL=${{ vars.VITE_BASIC_BCEID_REGISTRATION_URL }}
            VITE_BUSINESS_BCEID_REGISTRATION_URL=${{ vars.VITE_BUSINESS_BCEID_REGISTRATION_URL }}
            VITE_BCSC_REGISTRATION_URL=${{ vars.VITE_BCSC_REGISTRATION_URL }}
            VITE_BCEID_URL=${{ vars.VITE_BCEID_URL }}
            VITE_SITEMINDER_LOGOUT_URL=${{ vars.VITE_SITEMINDER_LOGOUT_URL }}
            VITE_KEYCLOAK_LOGOUT_URL=${{ vars.VITE_KEYCLOAK_LOGOUT_URL }}
            VITE_POST_LOGOUT_REDIRECT_URL=${{ vars.VITE_POST_LOGOUT_REDIRECT_URL }}
            VITE_RELEASE_VERSION=test-${{ github.event.inputs.branch }}@${{ env.GITHUB_SHA }}
      - name: Push to Openshift Registry using Service Account
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: test-hous-permit-portal
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.BUILDER_USERNAME }}
          password: ${{ secrets.BUILDER_TOKEN }}
      - name: Push Docker Image to JFrog Artifactory
        run: |
          # Log in to JFrog Artifactory
          echo "${{ secrets.ARTIFACTORY_API_KEY }}" | docker login ${{ secrets.ARTIFACTORY_URL }} -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

          # Tag the image to push to the JFrog Artifactory
          docker test-hous-permit-portal:latest ${{ secrets.ARTIFACTORY_URL }}/bbb1-hous-permit-portal/test:${{ env.GITHUB_SHA }}
          docker test-hous-permit-portal:latest ${{ secrets.ARTIFACTORY_URL }}/bbb1-hous-permit-portal/test:latest

          # Push the image to Artifactory
          docker push ${{ secrets.ARTIFACTORY_URL }}/bbb1-hous-permit-portal/test:${{ env.GITHUB_SHA }}
          docker push ${{ secrets.ARTIFACTORY_URL }}/bbb1-hous-permit-portall/test:latest
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
